name: Create Release from Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Existing tag name to create release from (e.g., 2.3)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag hash
        id: tag
        run: |
          # Verify tag exists
          if ! git rev-parse --verify "refs/tags/${{ github.event.inputs.tag_name }}" >/dev/null 2>&1; then
            echo "::error::Tag ${{ github.event.inputs.tag_name }} does not exist"
            exit 1
          fi
          echo "tag_hash=$(git rev-parse ${{ github.event.inputs.tag_name }})" >> $GITHUB_OUTPUT
          # Checkout the specific tag
          git checkout ${{ github.event.inputs.tag_name }}

      - name: Convert Estonian MD to PDF
        uses: docker://pandoc/latex:latest
        with:
          args: |
            mittefunktsionaalsed-nouded.md \
            -o mittefunktsionaalsed-nouded.pdf \
            --pdf-engine=xelatex \
            --variable geometry:margin=20mm \
            --variable mainfont="DejaVu Sans" \
            --variable monofont="DejaVu Sans Mono" \
            --variable fontsize=11pt \
            --metadata title="Mittefunktsionaalsed nõuded ${{ github.event.inputs.tag_name }}" \
            --metadata date="${{ github.event.repository.created_at }}" \
            --metadata commit="${{ steps.tag.outputs.tag_hash }}"

      - name: Convert English MD to PDF
        uses: docker://pandoc/latex:latest
        with:
          args: |
            mittefunktsionaalsed-nouded.en.md \
            -o mittefunktsionaalsed-nouded.en.pdf \
            --pdf-engine=xelatex \
            --variable geometry:margin=20mm \
            --variable mainfont="DejaVu Sans" \
            --variable monofont="DejaVu Sans Mono" \
            --variable fontsize=11pt \
            --metadata title="Non-functional Requirements ${{ github.event.inputs.tag_name }}" \
            --metadata date="${{ github.event.repository.created_at }}" \
            --metadata commit="${{ steps.tag.outputs.tag_hash }}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          files: |
            mittefunktsionaalsed-nouded.pdf
            mittefunktsionaalsed-nouded.en.pdf
            mittefunktsionaalsed-nouded.md
            mittefunktsionaalsed-nouded.en.md
          body: |
            ## Tarne ${{ github.event.inputs.tag_name }}

            Käesolev tarne sisaldab eesti- ja inglisekeelset versiooni mittefunktsionaalsete nõuete dokumendist Markdown ja PDF formaadis.
            
            This release includes both Estonian and English versions of the non-functional requirements document in Markdown and PDF formats.

            ### Failid:
            - mittefunktsionaalsed-nouded.md (Eesti, Markdown)
            - mittefunktsionaalsed-nouded.pdf (Eesti, PDF)
            - mittefunktsionaalsed-nouded.en.md (English, Markdown)
            - mittefunktsionaalsed-nouded.en.pdf (English, PDF)

            ### Metaandmed:
            - Commit: `${{ steps.tag.outputs.tag_hash }}`
            - Versioon: `${{ github.event.inputs.tag_name }}`
            - Aeg: `${{ github.event.repository.created_at }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 