name: Create Release from Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Existing tag name to create release from (e.g., 2.3)'
        required: true
        type: string

permissions:
  contents: write
  packages: read

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag hash
        id: tag
        run: |
          # Verify tag exists
          if ! git rev-parse --verify "refs/tags/${{ github.event.inputs.tag_name }}" >/dev/null 2>&1; then
            echo "::error::Tag ${{ github.event.inputs.tag_name }} does not exist"
            exit 1
          fi
          echo "tag_hash=$(git rev-parse ${{ github.event.inputs.tag_name }})" >> $GITHUB_OUTPUT
          # Checkout the specific tag
          git checkout ${{ github.event.inputs.tag_name }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull PDF generation image
        run: docker pull ghcr.io/${{ github.repository }}/pdf-generator:main

      - name: Generate PDFs
        run: |
          # Create output directory if it doesn't exist
          mkdir -p output
          # Run the container with proper volume mounts
          docker run --rm \
            -v "$(pwd)/mittefunktsionaalsed-nouded.md:/app/input/mittefunktsionaalsed-nouded.md" \
            -v "$(pwd)/mittefunktsionaalsed-nouded.en.md:/app/input/mittefunktsionaalsed-nouded.en.md" \
            -v "$(pwd)/output:/app/output" \
            ghcr.io/${{ github.repository }}/pdf-generator:main

      - name: Verify PDF generation
        run: |
          if [ ! -f "output/mittefunktsionaalsed-nouded.pdf" ] || [ ! -f "output/mittefunktsionaalsed-nouded.en.pdf" ]; then
            echo "::error::PDF files were not generated successfully"
            exit 1
          fi
          echo "PDF files generated successfully"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          files: |
            output/mittefunktsionaalsed-nouded.pdf
            output/mittefunktsionaalsed-nouded.en.pdf
            mittefunktsionaalsed-nouded.md
            mittefunktsionaalsed-nouded.en.md
          body: |
            ## Tarne ${{ github.event.inputs.tag_name }}

            Käesolev tarne sisaldab eesti- ja inglisekeelset versiooni mittefunktsionaalsete nõuete dokumendist Markdown ja PDF formaadis.
            
            This release includes both Estonian and English versions of the non-functional requirements document in Markdown and PDF formats.

            ### Failid:
            - mittefunktsionaalsed-nouded.md (Eesti, Markdown)
            - mittefunktsionaalsed-nouded.pdf (Eesti, PDF)
            - mittefunktsionaalsed-nouded.en.md (English, Markdown)
            - mittefunktsionaalsed-nouded.en.pdf (English, PDF)

            ### Metaandmed:
            - Commit: `${{ steps.tag.outputs.tag_hash }}`
            - Versioon: `${{ github.event.inputs.tag_name }}`
            - Aeg: `${{ github.event.repository.created_at }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 